import { useState, useEffect } from 'react'
import { usePassageStore } from '../../stores/passageStore'
import { bhsaAPI, mapsAPI } from '../../services/api'
import { toast } from 'sonner'
import { DiscourseRelationCreate } from '../../types'
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card'
import { Button } from '../ui/button'
import { Badge } from '../ui/badge'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from '../ui/dialog'
import { MessageSquare, ArrowRight, Plus, Trash2, Loader2, Save, CheckCircle } from 'lucide-react'

const DISCOURSE_RELATIONS = [
    { value: 'sequence', label: 'Sequence (and then)' },
    { value: 'simultaneous', label: 'Simultaneous (while)' },
    { value: 'cause', label: 'Cause (because)' },
    { value: 'result', label: 'Result (therefore)' },
    { value: 'purpose', label: 'Purpose (in order to)' },
    { value: 'condition', label: 'Condition (if)' },
    { value: 'concession', label: 'Concession (although)' },
    { value: 'contrast', label: 'Contrast (but)' },
    { value: 'explanation', label: 'Explanation (that is)' },
    { value: 'elaboration', label: 'Elaboration' },
    { value: 'background', label: 'Background' },
    { value: 'setting', label: 'Setting' }
]

function Stage5Discourse() {
    const {
        passageData,
        discourse,
        setDiscourse,
        events,
        loading,
        setLoading,
        error,
        setError,
        trackEdit,
        aiSnapshot
    } = usePassageStore()
    const [showModal, setShowModal] = useState(false)
    const [saving, setSaving] = useState(false)
    const [saved, setSaved] = useState(false)
    const [formData, setFormData] = useState<DiscourseRelationCreate>({
        relationType: 'sequence',
        sourceId: '',
        targetId: ''
    })

    useEffect(() => {
        // Only fetch from DB if no discourse in store (avoid overwriting AI-generated data)
        if (passageData?.id && discourse.length === 0) {
            fetchDiscourse(passageData.id)
        }
    }, [passageData?.id])

    const fetchDiscourse = async (passageId: string) => {
        try {
            setLoading(true)
            const data = await bhsaAPI.getDiscourse(passageId)
            setDiscourse(data)
        } catch (err: any) {
            console.error('Failed to fetch discourse:', err)
            setError(err.response?.data?.detail || 'Failed to fetch discourse')
        } finally {
            setLoading(false)
        }
    }

    const handleCreate = () => {
        setFormData({
            relationType: 'sequence',
            sourceId: events[0]?.id || '',
            targetId: events[1]?.id || ''
        })
        setShowModal(true)
    }

    const handleSubmit = async () => {
        if (!passageData?.id) return

        if (!formData.sourceId || !formData.targetId) {
            alert('Please select both source and target events')
            return
        }

        try {
            setLoading(true)
            const created = await bhsaAPI.createDiscourse(passageData.id, formData)
            setDiscourse([...discourse, created])

            // Track creation
            if (aiSnapshot) {
                trackEdit('create', 'discourse', created.id, undefined, undefined, undefined, false)
            }

            setShowModal(false)
        } catch (err: any) {
            console.error('Error saving discourse relation:', err)
            setError(err.response?.data?.detail || 'Failed to save discourse relation')
        } finally {
            setLoading(false)
        }
    }

    const handleDelete = async (id: string) => {
        if (!confirm('Are you sure you want to delete this relation?')) return

        try {
            setLoading(true)
            await bhsaAPI.deleteDiscourse(id)
            setDiscourse(discourse.filter(d => d.id !== id))

            // Track deletion
            if (aiSnapshot) {
                const original = discourse.find(d => d.id === id)
                // Try to infer if it was AI generated by properties
                let wasAiGenerated = false
                if (aiSnapshot.discourse && original) {
                    wasAiGenerated = aiSnapshot.discourse.some((d: any) =>
                        d.relationType === original.relationType &&
                        // Matching source/target by ID is tricky in snapshot vs DB, could match logic if needed 
                        // For now we assume if we have a match on type it *might* be it, 
                        // but ideally we'd need better matching logic if IDs drift.
                        // However, simpler is tracking deletion of ANY object in an AI session.
                        true
                    )
                }
                trackEdit('delete', 'discourse', id, undefined, undefined, undefined, wasAiGenerated)
            }
        } catch (err: any) {
            console.error('Error deleting discourse relation:', err)
            setError(err.response?.data?.detail || 'Failed to delete discourse relation')
        } finally {
            setLoading(false)
        }
    }

    const getEventDisplay = (eventId: string) => {
        // Look up by id (UUID) or eventId (e.g. "e1", "e2")
        const ev = events.find(e => e.id === eventId || e.eventId === eventId)
        return ev ? { id: ev.eventId, core: ev.eventCore } : { id: eventId, core: 'Unknown' }
    }

    const getRelationLabel = (type: string) => {
        const rel = DISCOURSE_RELATIONS.find(r => r.value === type)
        return rel ? rel.label : type
    }

    const handleFinalize = async () => {
        if (!passageData?.id) {
            console.error('Cannot finalize: passageData.id is missing', passageData)
            toast.error('Error: No active passage found', {
                description: 'Please go back to Stage 1 and load a passage to continue.'
            })
            return
        }
        try {
            setSaving(true)
            await mapsAPI.finalizePassage(passageData.id)
            setSaved(true)
        } catch (err: any) {
            console.error('Error finalizing passage:', err)
            setError(err.response?.data?.detail || 'Failed to save analysis')
        } finally {
            setSaving(false)
        }
    }

    if (!passageData) {
        return (
            <Card className="border-dashed">
                <CardContent className="py-12 text-center text-verde/60">
                    <MessageSquare className="w-12 h-12 mx-auto mb-4 opacity-30" />
                    <p>Please fetch a passage in Stage 1 first.</p>
                </CardContent>
            </Card>
        )
    }

    return (
        <div className="space-y-6">
            {/* Stage header */}
            <div className="flex items-start justify-between">
                <div>
                    <h2 className="text-2xl font-bold text-preto flex items-center gap-2">
                        <MessageSquare className="w-6 h-6 text-telha" />
                        Stage 5: Discourse
                    </h2>
                    <p className="text-verde mt-1">Define high-level structure and relationships between events.</p>
                </div>
                <Button onClick={handleCreate} disabled={events.length < 2} className="gap-2">
                    <Plus className="w-4 h-4" />
                    Add Relation
                </Button>
            </div>

            {error && (
                <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg">
                    {error}
                </div>
            )}

            {/* Discourse relations */}
            <div className="space-y-3">
                {discourse.map((d, idx) => {
                    const source = getEventDisplay(d.sourceId)
                    const target = getEventDisplay(d.targetId)

                    return (
                        <Card key={d.id || `d-${d.sourceId}-${d.targetId}-${idx}`} className="group">
                            <CardContent className="p-4">
                                <div className="flex items-center justify-between">
                                    <div className="flex items-center gap-4 flex-1">
                                        {/* Source event */}
                                        <div className="flex-1 bg-areia/20 rounded-lg p-3 text-center">
                                            <span className="text-xs text-verde/60">{source.id}</span>
                                            <p className="font-semibold text-preto">{source.core}</p>
                                        </div>

                                        {/* Relation */}
                                        <div className="flex flex-col items-center gap-1 px-4">
                                            <Badge variant="success" className="text-xs uppercase">
                                                {d.relationType}
                                            </Badge>
                                            <ArrowRight className="w-5 h-5 text-telha" />
                                        </div>

                                        {/* Target event */}
                                        <div className="flex-1 bg-areia/20 rounded-lg p-3 text-center">
                                            <span className="text-xs text-verde/60">{target.id}</span>
                                            <p className="font-semibold text-preto">{target.core}</p>
                                        </div>
                                    </div>

                                    <Button
                                        variant="ghost"
                                        size="sm"
                                        className="ml-4 opacity-0 group-hover:opacity-100 text-red-500"
                                        onClick={() => handleDelete(d.id)}
                                    >
                                        <Trash2 className="w-4 h-4" />
                                    </Button>
                                </div>
                            </CardContent>
                        </Card>
                    )
                })}
            </div>

            {discourse.length === 0 && (
                <Card className="border-dashed">
                    <CardContent className="py-12 text-center text-verde/60">
                        <MessageSquare className="w-12 h-12 mx-auto mb-4 opacity-30" />
                        <p>No discourse relations yet. Add events in Stage 4 first, then define their relationships here.</p>
                    </CardContent>
                </Card>
            )}

            {events.length < 2 && (
                <div className="bg-azul/10 border border-azul/30 text-verde px-4 py-3 rounded-lg">
                    You need at least 2 events to create discourse relations. Please add events in Stage 4.
                </div>
            )}

            {/* Complete & Save Section */}
            <Card className="border-2 border-verde-claro/30 bg-verde-claro/5">
                <CardContent className="py-6">
                    <div className="flex items-center justify-between">
                        <div>
                            <h3 className="text-lg font-semibold text-preto flex items-center gap-2">
                                {saved ? (
                                    <>
                                        <CheckCircle className="w-5 h-5 text-verde-claro" />
                                        Analysis Saved!
                                    </>
                                ) : (
                                    <>
                                        <Save className="w-5 h-5 text-verde-claro" />
                                        Complete Your Analysis
                                    </>
                                )}
                            </h3>
                            <p className="text-sm text-verde mt-1">
                                {saved
                                    ? 'Your meaning map has been saved to the database. View it in "My Saved Maps".'
                                    : 'Save this analysis to the database. You can download it as JSON later from "My Saved Maps".'
                                }
                            </p>
                        </div>
                        <Button
                            onClick={handleFinalize}
                            disabled={saving || saved}
                            variant={saved ? 'outline' : 'default'}
                            className="gap-2"
                        >
                            {saving ? (
                                <Loader2 className="w-4 h-4 animate-spin" />
                            ) : saved ? (
                                <CheckCircle className="w-4 h-4" />
                            ) : (
                                <Save className="w-4 h-4" />
                            )}
                            {saving ? 'Saving...' : saved ? 'Saved' : 'Complete & Save'}
                        </Button>
                    </div>
                </CardContent>
            </Card>

            {/* Add Modal */}
            <Dialog open={showModal} onOpenChange={setShowModal}>
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle>New Discourse Relation</DialogTitle>
                        <DialogDescription>Connect two events with a semantic relationship.</DialogDescription>
                    </DialogHeader>

                    <div className="space-y-4 py-4">
                        <div>
                            <label className="text-sm font-medium text-preto mb-1.5 block">Source Event</label>
                            <Select value={formData.sourceId} onValueChange={(v) => setFormData({ ...formData, sourceId: v })}>
                                <SelectTrigger>
                                    <SelectValue placeholder="Select event..." />
                                </SelectTrigger>
                                <SelectContent>
                                    {events.map((ev, idx) => (
                                        <SelectItem key={ev.id || `ev-${ev.eventId}-${idx}`} value={ev.id || ev.eventId}>
                                            {ev.eventId}: {ev.eventCore} ({ev.category})
                                        </SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>

                        <div>
                            <label className="text-sm font-medium text-preto mb-1.5 block">Relation Type</label>
                            <Select value={formData.relationType} onValueChange={(v) => setFormData({ ...formData, relationType: v })}>
                                <SelectTrigger>
                                    <SelectValue />
                                </SelectTrigger>
                                <SelectContent>
                                    {DISCOURSE_RELATIONS.map(r => (
                                        <SelectItem key={r.value} value={r.value}>{r.label}</SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>

                        <div>
                            <label className="text-sm font-medium text-preto mb-1.5 block">Target Event</label>
                            <Select value={formData.targetId} onValueChange={(v) => setFormData({ ...formData, targetId: v })}>
                                <SelectTrigger>
                                    <SelectValue placeholder="Select event..." />
                                </SelectTrigger>
                                <SelectContent>
                                    {events.map((ev, idx) => (
                                        <SelectItem key={ev.id || `ev-${ev.eventId}-${idx}`} value={ev.id || ev.eventId}>
                                            {ev.eventId}: {ev.eventCore} ({ev.category})
                                        </SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>
                    </div>

                    <DialogFooter>
                        <Button variant="outline" onClick={() => setShowModal(false)}>Cancel</Button>
                        <Button onClick={handleSubmit} disabled={loading}>
                            {loading ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : null}
                            Create Relation
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </div>
    )
}

export default Stage5Discourse
